# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Harlock123.AVASvgMaker
PackageVersion: 1.13.0
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
ReleaseDate: '2026-09-15'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Harlock123/AVASvgMaker/releases/download/v1.13.0/AVASvgMaker-1.13.0-win-x64.zip
    InstallerSha256: CCF522976BF870A589DA34B3F85D778FA36893246F1C709139E912CA7D5063CA
    NestedInstallerFiles:
      - RelativeFilePath: AVASvgMaker.exe
        PortableCommandAlias: avasvgmaker
  - Architecture: arm64
    InstallerUrl: https://github.com/Harlock123/AVASvgMaker/releases/download/v1.13.0/AVASvgMaker-1.13.0-win-arm64.zip
    InstallerSha256: 80ECFEEF551EDE7BB2E6B25D2FF6F75832F5A3DA9B8A0E9B70B03161657F26E9
    NestedInstallerFiles:
      - RelativeFilePath: AVASvgMaker.exe
        PortableCommandAlias: avasvgmaker
ManifestType: installer
ManifestVersion: 1.6.0
